/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "api.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HelloRequest, HelloRequest, AUTO)


PB_BIND(HelloResponse, HelloResponse, AUTO)


PB_BIND(AuthenticationRequest, AuthenticationRequest, AUTO)


PB_BIND(AuthenticationResponse, AuthenticationResponse, AUTO)


PB_BIND(DisconnectRequest, DisconnectRequest, AUTO)


PB_BIND(DisconnectResponse, DisconnectResponse, AUTO)


PB_BIND(PingRequest, PingRequest, AUTO)


PB_BIND(PingResponse, PingResponse, AUTO)


PB_BIND(DeviceInfoRequest, DeviceInfoRequest, AUTO)


PB_BIND(AreaInfo, AreaInfo, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(DeviceInfoResponse, DeviceInfoResponse, 2)


PB_BIND(ListEntitiesRequest, ListEntitiesRequest, AUTO)


PB_BIND(ListEntitiesDoneResponse, ListEntitiesDoneResponse, AUTO)


PB_BIND(SubscribeStatesRequest, SubscribeStatesRequest, AUTO)


PB_BIND(ListEntitiesBinarySensorResponse, ListEntitiesBinarySensorResponse, AUTO)


PB_BIND(BinarySensorStateResponse, BinarySensorStateResponse, AUTO)


PB_BIND(ListEntitiesCoverResponse, ListEntitiesCoverResponse, AUTO)


PB_BIND(CoverStateResponse, CoverStateResponse, AUTO)


PB_BIND(CoverCommandRequest, CoverCommandRequest, AUTO)


PB_BIND(ListEntitiesFanResponse, ListEntitiesFanResponse, AUTO)


PB_BIND(FanStateResponse, FanStateResponse, AUTO)


PB_BIND(FanCommandRequest, FanCommandRequest, AUTO)


PB_BIND(ListEntitiesLightResponse, ListEntitiesLightResponse, AUTO)


PB_BIND(LightStateResponse, LightStateResponse, AUTO)


PB_BIND(LightCommandRequest, LightCommandRequest, AUTO)


PB_BIND(ListEntitiesSensorResponse, ListEntitiesSensorResponse, AUTO)


PB_BIND(SensorStateResponse, SensorStateResponse, AUTO)


PB_BIND(ListEntitiesSwitchResponse, ListEntitiesSwitchResponse, AUTO)


PB_BIND(SwitchStateResponse, SwitchStateResponse, AUTO)


PB_BIND(SwitchCommandRequest, SwitchCommandRequest, AUTO)


PB_BIND(ListEntitiesTextSensorResponse, ListEntitiesTextSensorResponse, AUTO)


PB_BIND(TextSensorStateResponse, TextSensorStateResponse, AUTO)


PB_BIND(SubscribeLogsRequest, SubscribeLogsRequest, AUTO)


PB_BIND(SubscribeLogsResponse, SubscribeLogsResponse, AUTO)


PB_BIND(NoiseEncryptionSetKeyRequest, NoiseEncryptionSetKeyRequest, AUTO)


PB_BIND(NoiseEncryptionSetKeyResponse, NoiseEncryptionSetKeyResponse, AUTO)


PB_BIND(SubscribeHomeassistantServicesRequest, SubscribeHomeassistantServicesRequest, AUTO)


PB_BIND(HomeassistantServiceMap, HomeassistantServiceMap, AUTO)


PB_BIND(HomeassistantActionRequest, HomeassistantActionRequest, AUTO)


PB_BIND(HomeassistantActionResponse, HomeassistantActionResponse, AUTO)


PB_BIND(SubscribeHomeAssistantStatesRequest, SubscribeHomeAssistantStatesRequest, AUTO)


PB_BIND(SubscribeHomeAssistantStateResponse, SubscribeHomeAssistantStateResponse, AUTO)


PB_BIND(HomeAssistantStateResponse, HomeAssistantStateResponse, AUTO)


PB_BIND(GetTimeRequest, GetTimeRequest, AUTO)


PB_BIND(GetTimeResponse, GetTimeResponse, AUTO)


PB_BIND(ListEntitiesServicesArgument, ListEntitiesServicesArgument, AUTO)


PB_BIND(ListEntitiesServicesResponse, ListEntitiesServicesResponse, AUTO)


PB_BIND(ExecuteServiceArgument, ExecuteServiceArgument, AUTO)


PB_BIND(ExecuteServiceRequest, ExecuteServiceRequest, AUTO)


PB_BIND(ExecuteServiceResponse, ExecuteServiceResponse, AUTO)


PB_BIND(ListEntitiesCameraResponse, ListEntitiesCameraResponse, AUTO)


PB_BIND(CameraImageResponse, CameraImageResponse, AUTO)


PB_BIND(CameraImageRequest, CameraImageRequest, AUTO)


PB_BIND(ListEntitiesClimateResponse, ListEntitiesClimateResponse, 2)


PB_BIND(ClimateStateResponse, ClimateStateResponse, AUTO)


PB_BIND(ClimateCommandRequest, ClimateCommandRequest, AUTO)


PB_BIND(ListEntitiesWaterHeaterResponse, ListEntitiesWaterHeaterResponse, AUTO)


PB_BIND(WaterHeaterStateResponse, WaterHeaterStateResponse, AUTO)


PB_BIND(WaterHeaterCommandRequest, WaterHeaterCommandRequest, AUTO)


PB_BIND(ListEntitiesNumberResponse, ListEntitiesNumberResponse, AUTO)


PB_BIND(NumberStateResponse, NumberStateResponse, AUTO)


PB_BIND(NumberCommandRequest, NumberCommandRequest, AUTO)


PB_BIND(ListEntitiesSelectResponse, ListEntitiesSelectResponse, AUTO)


PB_BIND(SelectStateResponse, SelectStateResponse, AUTO)


PB_BIND(SelectCommandRequest, SelectCommandRequest, AUTO)


PB_BIND(ListEntitiesSirenResponse, ListEntitiesSirenResponse, AUTO)


PB_BIND(SirenStateResponse, SirenStateResponse, AUTO)


PB_BIND(SirenCommandRequest, SirenCommandRequest, AUTO)


PB_BIND(ListEntitiesLockResponse, ListEntitiesLockResponse, AUTO)


PB_BIND(LockStateResponse, LockStateResponse, AUTO)


PB_BIND(LockCommandRequest, LockCommandRequest, AUTO)


PB_BIND(ListEntitiesButtonResponse, ListEntitiesButtonResponse, AUTO)


PB_BIND(ButtonCommandRequest, ButtonCommandRequest, AUTO)


PB_BIND(MediaPlayerSupportedFormat, MediaPlayerSupportedFormat, AUTO)


PB_BIND(ListEntitiesMediaPlayerResponse, ListEntitiesMediaPlayerResponse, AUTO)


PB_BIND(MediaPlayerStateResponse, MediaPlayerStateResponse, AUTO)


PB_BIND(MediaPlayerCommandRequest, MediaPlayerCommandRequest, AUTO)


PB_BIND(SubscribeBluetoothLEAdvertisementsRequest, SubscribeBluetoothLEAdvertisementsRequest, AUTO)


PB_BIND(BluetoothServiceData, BluetoothServiceData, AUTO)


PB_BIND(BluetoothLEAdvertisementResponse, BluetoothLEAdvertisementResponse, AUTO)


PB_BIND(BluetoothLERawAdvertisement, BluetoothLERawAdvertisement, AUTO)


PB_BIND(BluetoothLERawAdvertisementsResponse, BluetoothLERawAdvertisementsResponse, AUTO)


PB_BIND(BluetoothDeviceRequest, BluetoothDeviceRequest, AUTO)


PB_BIND(BluetoothDeviceConnectionResponse, BluetoothDeviceConnectionResponse, AUTO)


PB_BIND(BluetoothGATTGetServicesRequest, BluetoothGATTGetServicesRequest, AUTO)


PB_BIND(BluetoothGATTDescriptor, BluetoothGATTDescriptor, AUTO)


PB_BIND(BluetoothGATTCharacteristic, BluetoothGATTCharacteristic, AUTO)


PB_BIND(BluetoothGATTService, BluetoothGATTService, AUTO)


PB_BIND(BluetoothGATTGetServicesResponse, BluetoothGATTGetServicesResponse, AUTO)


PB_BIND(BluetoothGATTGetServicesDoneResponse, BluetoothGATTGetServicesDoneResponse, AUTO)


PB_BIND(BluetoothGATTReadRequest, BluetoothGATTReadRequest, AUTO)


PB_BIND(BluetoothGATTReadResponse, BluetoothGATTReadResponse, AUTO)


PB_BIND(BluetoothGATTWriteRequest, BluetoothGATTWriteRequest, AUTO)


PB_BIND(BluetoothGATTReadDescriptorRequest, BluetoothGATTReadDescriptorRequest, AUTO)


PB_BIND(BluetoothGATTWriteDescriptorRequest, BluetoothGATTWriteDescriptorRequest, AUTO)


PB_BIND(BluetoothGATTNotifyRequest, BluetoothGATTNotifyRequest, AUTO)


PB_BIND(BluetoothGATTNotifyDataResponse, BluetoothGATTNotifyDataResponse, AUTO)


PB_BIND(SubscribeBluetoothConnectionsFreeRequest, SubscribeBluetoothConnectionsFreeRequest, AUTO)


PB_BIND(BluetoothConnectionsFreeResponse, BluetoothConnectionsFreeResponse, AUTO)


PB_BIND(BluetoothGATTErrorResponse, BluetoothGATTErrorResponse, AUTO)


PB_BIND(BluetoothGATTWriteResponse, BluetoothGATTWriteResponse, AUTO)


PB_BIND(BluetoothGATTNotifyResponse, BluetoothGATTNotifyResponse, AUTO)


PB_BIND(BluetoothDevicePairingResponse, BluetoothDevicePairingResponse, AUTO)


PB_BIND(BluetoothDeviceUnpairingResponse, BluetoothDeviceUnpairingResponse, AUTO)


PB_BIND(UnsubscribeBluetoothLEAdvertisementsRequest, UnsubscribeBluetoothLEAdvertisementsRequest, AUTO)


PB_BIND(BluetoothDeviceClearCacheResponse, BluetoothDeviceClearCacheResponse, AUTO)


PB_BIND(BluetoothScannerStateResponse, BluetoothScannerStateResponse, AUTO)


PB_BIND(BluetoothScannerSetModeRequest, BluetoothScannerSetModeRequest, AUTO)


PB_BIND(SubscribeVoiceAssistantRequest, SubscribeVoiceAssistantRequest, AUTO)


PB_BIND(VoiceAssistantAudioSettings, VoiceAssistantAudioSettings, AUTO)


PB_BIND(VoiceAssistantRequest, VoiceAssistantRequest, AUTO)


PB_BIND(VoiceAssistantResponse, VoiceAssistantResponse, AUTO)


PB_BIND(VoiceAssistantEventData, VoiceAssistantEventData, AUTO)


PB_BIND(VoiceAssistantEventResponse, VoiceAssistantEventResponse, AUTO)


PB_BIND(VoiceAssistantAudio, VoiceAssistantAudio, AUTO)


PB_BIND(VoiceAssistantTimerEventResponse, VoiceAssistantTimerEventResponse, AUTO)


PB_BIND(VoiceAssistantAnnounceRequest, VoiceAssistantAnnounceRequest, AUTO)


PB_BIND(VoiceAssistantAnnounceFinished, VoiceAssistantAnnounceFinished, AUTO)


PB_BIND(VoiceAssistantWakeWord, VoiceAssistantWakeWord, AUTO)


PB_BIND(VoiceAssistantExternalWakeWord, VoiceAssistantExternalWakeWord, AUTO)


PB_BIND(VoiceAssistantConfigurationRequest, VoiceAssistantConfigurationRequest, AUTO)


PB_BIND(VoiceAssistantConfigurationResponse, VoiceAssistantConfigurationResponse, AUTO)


PB_BIND(VoiceAssistantSetConfiguration, VoiceAssistantSetConfiguration, AUTO)


PB_BIND(ListEntitiesAlarmControlPanelResponse, ListEntitiesAlarmControlPanelResponse, AUTO)


PB_BIND(AlarmControlPanelStateResponse, AlarmControlPanelStateResponse, AUTO)


PB_BIND(AlarmControlPanelCommandRequest, AlarmControlPanelCommandRequest, AUTO)


PB_BIND(ListEntitiesTextResponse, ListEntitiesTextResponse, AUTO)


PB_BIND(TextStateResponse, TextStateResponse, AUTO)


PB_BIND(TextCommandRequest, TextCommandRequest, AUTO)


PB_BIND(ListEntitiesDateResponse, ListEntitiesDateResponse, AUTO)


PB_BIND(DateStateResponse, DateStateResponse, AUTO)


PB_BIND(DateCommandRequest, DateCommandRequest, AUTO)


PB_BIND(ListEntitiesTimeResponse, ListEntitiesTimeResponse, AUTO)


PB_BIND(TimeStateResponse, TimeStateResponse, AUTO)


PB_BIND(TimeCommandRequest, TimeCommandRequest, AUTO)


PB_BIND(ListEntitiesEventResponse, ListEntitiesEventResponse, AUTO)


PB_BIND(EventResponse, EventResponse, AUTO)


PB_BIND(ListEntitiesValveResponse, ListEntitiesValveResponse, AUTO)


PB_BIND(ValveStateResponse, ValveStateResponse, AUTO)


PB_BIND(ValveCommandRequest, ValveCommandRequest, AUTO)


PB_BIND(ListEntitiesDateTimeResponse, ListEntitiesDateTimeResponse, AUTO)


PB_BIND(DateTimeStateResponse, DateTimeStateResponse, AUTO)


PB_BIND(DateTimeCommandRequest, DateTimeCommandRequest, AUTO)


PB_BIND(ListEntitiesUpdateResponse, ListEntitiesUpdateResponse, AUTO)


PB_BIND(UpdateStateResponse, UpdateStateResponse, AUTO)


PB_BIND(UpdateCommandRequest, UpdateCommandRequest, AUTO)


PB_BIND(ZWaveProxyFrame, ZWaveProxyFrame, AUTO)


PB_BIND(ZWaveProxyRequest, ZWaveProxyRequest, AUTO)


PB_BIND(ListEntitiesInfraredResponse, ListEntitiesInfraredResponse, AUTO)


PB_BIND(InfraredRFTransmitRawTimingsRequest, InfraredRFTransmitRawTimingsRequest, AUTO)


PB_BIND(InfraredRFReceiveEvent, InfraredRFReceiveEvent, AUTO)















































































